== Site management: Guides

Configuring guides and other metadata for the Snowdrop website requires http://git-scm.com/download[Git] and a text editor. It also helps to have an asciidoc preview tool such as https://chrome.google.com/webstore/detail/asciidoctorjs-live-previe/iaalpfgpbocpdfblpnhhgllgbdbchmia?hl=en[Asciidoctor.js Live Preview] for Chrome. Guides are written in Asciidoc format.

=== Creating a new guide

* Clone the Snowdrop Docs repository: https://github.com/snowdrop/snowdrop-docs
* Place a new `*.adoc` file in the `site/guides` directory (or host your source asciidoc file on the public internet, you will need its URL later):
+
----
snowdrop-docs/site/guides/
    guide-a.adoc
    guide-b.adoc
    your-new-guide.adoc
----
* Add an entry to the site config.json file: https://github.com/snowdrop/snowdrop-docs/blob/master/site/config.json
* *IMPORTANT*: Validate the JSON before pushing changes: https://jsonlint.com/
* Once your guide has been configured. Push changes to the `snowdrop-site` repository.
* Do not re-build/re-deploy the Snowdrop website. Changes are publicly visible as soon as files are updated on GitHub.
* Changes may take several minutes to become visible on the Snowdrop website, as GitHub sometimes caches raw documents for a period of time.

=== Configuring existing guides
Similar to creating a new guide, all existing guides and their metadata can be updated simply by editing the asciidoc source in-place (e.g. pushing changes to Git), or updating the metadata contained within the Snowdrop site https://github.com/snowdrop/snowdrop-docs/blob/master/site/config.json[config.json]. All changes pushed become live immediately. No rebuild of the site is necessary.

=== Guide configuration syntax
You can find the guides configuration array in the https://github.com/snowdrop/snowdrop-docs/blob/master/site/config.json[site config file]. It is recommended to use an existing entry as a template for new guides.

.config.json
[source,json]
----
guides: [
...
    "prerequisites": "",
    "tags": "build, cloud native"
  },
  ...
  {
    "type":"guide", # <1>
    "title":"Title of your new guide", # <2>
    "description":"A brief 150 or fewer characters description of the guide's purpose.", # <3>
    "urls": {
      "booster": "artifactId=istio-routing&groupId=me.snowdrop.booster&mission=istio-routing&runtime=spring-boot&runtimeVersion=current-community" # <4>
      "content":"https://raw.githubusercontent.com/snowdrop/snowdrop-docs/master/site/guides/your-new-guide.adoc", # <5>
      "documentation": "/guides/adding-configuring-guides" # <6>
      "source": "https://github.com/snowdrop/snowdrop-docs" # <7>
    },
    "prerequisites": "foo, bar, -hard", # <8>
    "enablements": "dal, lar, -easy", # <9>
    "tags": "baz, cab" # <10>
  },
  ...
  {
    "type":"guide",
    "title":"Configuring/adding a Guide",
...
],
----
<1> *The guide type:* Currently the only supported type is "guide".
<2> *The title of your new guide:* This should be 50 characters or less, or it may be truncated.
<3> *The description of your new guide:* This should be 150 characters or less, or it may be truncated.
<4> *Booster URL:* Parameters that are passed to the launcher to download a booster ZIP file. This is only necessary if your guide has a corresponding booster that is downloadable via the Snowdrop launcher.
<5> *Content URL:* This is the fully qualified URL to the source of your guide's content. This must link to an asciidoc file that is accessible via the public internet.
<6> *Documentation URL:* This is the path to external documentation (if any) referenced by your guide.
<7> *Source URL:* This is the path to the source code for your guide, or for the project it describes.
<8> *Prerequisite tags:* Specify tags of any guides that should be completed as a prerequisite step before beginning *this* guide. Any tags negated/prefixed with "-" the dash, or minus sign will cause matching guides to be excluded. Any tags prefixed with "+", the plus sign, require the corresponding guide to strictly include the specified tag in order to match.
<9> *Enablement tags:* Specify tags of any guides that can be completed as a followup, or "next steps", once *this* guide has been completed. Any tags negated/prefixed with "-" the dash, or minus sign will cause matching guides to be excluded. Any tags prefixed with "+", the plus sign, require the corresponding guide to strictly include the specified tag in order to match.
<10> *Tags:* Specify tags describing this guide. These are used when matching related content on the site, and also used when calculating prerequisites and enablements of other guides. (Tags cannot be negated.)

=== Using collapsible sections in guides
The SnowDrop website will automatically render second level sections as collapsible (link:https://github.com/snowdrop/snowdrop-docs/blob/master/site/guides/site/adding-configuring-guides.adoc[like this guide itself], for example).
This creates a visual aid that allows the reader to quickly navigate to parts of a document that they are interested, while skipping parts that are not pertinent, or useful to them. More information can be contained in each guide, and readers can explore at will.

NOTE:: Sections are collapsed by default until the reader clicks on its heading, or on its entry in the table of contents.

==== How to create a collapsible section
To create a collapsible section, use a second-level heading, like so:

.example-guide.adoc
[source,asciidoc]
----
=== This is a collapsible second-level section
Anything contained will be collapsed by default until the reader clicks on its heading, or on its entry in the table of contents.
----

NOTE:: Only second-level sections are collapsible, all others are displayed normally.

==== A more detailed example
This example shows how to use a collapsible section in the context of an entire guide/document.

.example-guide.adoc
[source,asciidoc]
----
= This is the document title

== This is a first level header

=== This is a collapsible second-level section

Example text just for example's sake, isn't this great!? Let's write some more examples so everyone is happy and exampled out.
+
.example-guide.adoc
[source,asciidoc]
....
This example contains an example, isn't it amusing?
....

=== This is another collapsible second-level section
Anything contained in this section will be collapsed by default

== This first-level section will not be collapsible

==== This is a third-level section
This section will not be collapsible because it is not contained within a second-level section
----

== Site management: Linked projects

The SnowDrop site can be configured to display contextual project information (related projects)
when viewing other content such as guides and news content. This allows guide authors to quickly provide
additional reference information to readers when their guide relates to content that is hosted on
another website (or belongs to another project or technology).

=== How to configure linked projects and tags

To add a linked project to the site, edit the site  https://github.com/snowdrop/snowdrop-docs/blob/master/site/config.json[config.json] file and add a new element
to the "projects" array, seen below:

==== Linked project syntax
.config.json
[source,json]
----
...
"projects": [
  {
    "name": "ProjectName", # <1>
    "description": "The project description.", # <2>
    "tag": "project-tag", # <3>
    "color": "#98BBD3", # <4>
    "urls":{
      "logo":"http://site.com/project-logo.png", # <5>
      "source":"https://github.com/my-organization/my-project", # <6>
      "website":"http://example.org/myproject" # <7>
    }
  },
  ...
]
...
----
<1> *Project name:* This will appear wherever project information is rendered (Should be maximum 20-30 characters)
<2> *Project description:* This will appear wherever project information is rendered, and should be relatively short. (Less than 80 characters in length)
<3> *Project tag:* The project will be rendered when guides or other content is tagged with this term.
<4> *Project color:* Hex code defining the project highlight color for tags and labels
<5> *Project logo URL:* Link to the project's logo. This should be roughly 60px x 60px (Square aspect ratio)
<6> *Source URL:* Link to the project's source repository
<7> *Website URL:* Link to the project's website

=== How to link a project to a guide

To display a linked project on a guide page, you must ensure that the project tag is added to the guide's tags.
Edit the site config.json file to modify your guide's tags:

.config.json
[source,json]
----
guides: [
  ...
  {
    "type":"guide",
    "title": ...,
    "description": ...,
    "urls": {
      ...
    },
    "prerequisites": ...,
    "enablements": ...,
    "tags": "foo, bar, project-tag, tag2" # <1>
  },
  ...
],
----
<1> Project tag is added to the guide's tags.

Notice that the project tag has been added to the guides list of "tags". Your linked project will now appear in the sidebar of the site when viewing this guide.
