=== Blog publication

=== Spring Boot + OpenTracing
28th of May 2018 by geoand

**Tags** : Spring Boot, OpenTracing

**Description** : Getting started with Spring Boot applications instrumented with OpenTracing in order to get tracing insights with minimal developer effort.


In a microservice topology, where an incoming HTTP call to the cluster could end up calling a host of other services, getting insights on the interactions of the individual services and performing debugging becomes complicated.

Distributed tracing gives developers and operators the ability to gain insights on the potentially complex interactions between microservices by painting a picture of what they look like in a graph form.


'''

28th of May 2018 by Developer

**Tags** : Spring Boot, Cloud Native Development

**Description** : Lorum ipsum dolor ipset this site is real and it continues to grow.
Lorum ipsum dolor ipset this site is real and it continues to grow.

Lorum ipsum dolor ipset this site is real and it continues to grow.

Formating info is available https://asciidoctor.org/docs/asciidoc-syntax-quick-reference/#horizontal-rules-and-page-breaks[here]

'''

=== New site is live!
/Snowdrop Developer - 2018-05-22/

Welcome to Snowdrop! We're glad you're here. Lorum ipsum dolor ipset this site is real and it continues to grow.

I have no idea how this is going to look. Let's try it out!

'''
