:page-layout: default
:page-title: http-api
:page-permalink: /guides/http-api

=== Spring Boot HTTP Api Booster

https://github.com/snowdrop/spring-boot-http-secured-booster[Git Project of the Spring HTTP API Quickstart]

The {name-mission-http-api} Mission provides a basic example of mapping business operations to a remote procedure call endpoint over HTTP using a REST framework. This corresponds to link:https://martinfowler.com/articles/richardsonMaturityModel.html#level0[Level 0 in the Richardson Maturity Model]. Creating an HTTP endpoint using REST and its underlying principals to define your API enables you to quickly prototype and design your API in a flexible manner.

More background information on REST is available in xref:about_rest[].

This is an introduction to the mechanics of opening a service that is called remotely. Specifically, this booster is an application that allows a user to:

* Execute an HTTP `GET` request on the `api/greeting` endpoint.
* Receive a response in JSON format with a payload consisting of the `Hello, World!` String.
* Execute an HTTP `GET` request on the `api/greeting` endpoint while passing in a String argument. This uses the `name` request parameter in the query string.
* Receive a response in JSON format with a payload of `Hello, $name!` with `$name` replaced by the value of the `name` parameter passed into the request.

.Design Tradeoffs
[width="100%",options="header"]
|====================================================================
|Pros           |Cons
a|
* Fast prototyping
* Flexible API Design
* HTTP endpoints allow clients to be language agnostic
a|
* As an application or service matures, the {name-mission-http-api} approach may not scale well to properly support a clean API design or use cases involving database interactions. Any operations involving shared, mutable state must be integrated with an appropriate backing datastore. All requests handled by an API designed in this manner will be scoped only to the container servicing the request. Therefore there is no guarantee that subsequent requests will be served by the same container.
|====================================================================

[[rest_build_and_deploy_booster]]
=== Build and Deploy Your Booster

- TODO -> add content of "include::booster-deploy-openshift-online.adoc"

// this is intentionally a level 3
==== Deploy Using the `oc` CLI Client

- TODO -> add content of "include::oc-client-deploy-booster-download-note.adoc"

. Get your authentication token for using the `oc` CLI client with your {OpenShiftOnline} account. You can find this in the _Command Line Tools_ section your {OpenShiftOnline} Web console.

. Authenticate your `oc` CLI client with your {OpenShiftOnline} account by using your authentication token.
+
[source,bash,options="nowrap",subs="attributes+"]
----
$ oc login {link-oso-auth} --token=MYTOKEN
----

. Create a new project in {OpenShiftOnline}.
+
[source,bash,options="nowrap",subs="attributes+"]
----
$ oc new-project {project-name}
----

. Navigate to the root directory of your booster.

. Use maven to start the deployment to {OpenShiftOnline}.
+
[source,bash,options="nowrap",subs="attributes+"]
----
$ mvn clean fabric8:deploy -Popenshift
----
+
This command uses the Fabric8 Maven Plugin to launch the S2I process on {OpenShiftOnline} and to start the pod.


. Check the status of your booster and ensure your pod is running.
+
[source,bash,options="nowrap",subs="attributes+"]
----
$ oc get pods -w
NAME                             READY     STATUS      RESTARTS   AGE
{app-name}-1-aaaaa               1/1       Running     0          58s
{app-name}-s2i-1-build           0/1       Completed   0          2m
----
+
You `app1` pod should have a status of `Running` once its fully deployed and started.

. Once your booster is deployed and started, determine its route.
+
.Example Route Information
[source,bash,options="nowrap",subs="attributes+"]
----
$ oc get routes
NAME                 HOST/PORT                                                     PATH      SERVICES        PORT      TERMINATION
{app-name}         {app-name}-{project-name}.1ab5.starter-us-east-1.openshiftapps.com      {app-name}      8080
----
+
A pod's route information gives you the base URL which you use to access it. In the example above, you would use `http://{app-name}-{project-name}.1ab5.starter-us-east-1.openshiftapps.com` as the base URL to access the application.


=== Deploy your Booster to a {OpenShiftLocal}

. Before you can use a {OpenShiftLocal}, you need to have it installed, configured, and running. You can find more details in link:{link-openshift-local-guide}[{openshift-local-guide-name}].

. Once you have a {OpenShiftLocal} running, check the console output for the URL you can use to access it.
+
.Example Console Output from a {OpenShiftLocal} Startup
[source,bash,options="nowrap",subs="attributes+"]
----
...
-- Removing temporary directory ... OK
-- Server Information ...
   OpenShift server started.
   The server is accessible via web console at:
       https://192.168.99.100:8443

   You are logged in as:
       User:     developer
       Password: developer

   To login as administrator:
       oc login -u system:admin
----

=== Deploy Using {launcher}

Once you have the {launcher} application link:{link-launcher-openshift-local-install-guide}[installed and configured],
navigate to it in {OpenShiftLocal} and use it to create and launch your booster.

=== Deploy Using the `oc` CLI Client

You can deploy your booster to {OpenShiftLocal} by following the same process as deploying a booster to {OpenShiftOnline}, but instead of using a {OpenShiftOnline} URL, use your {OpenShiftLocal} URL to access the Web console and with the `oc` CLI client.

== Interact with the Unmodified {SpringBoot} Booster

The booster provides a default HTTP endpoint that accepts GET requests.

. Use `curl` to execute a `GET` request against the booster. You can also use a browser to do this.
+
[source,bash,options="nowrap",subs="attributes+"]
----
$ curl http://{app-name}-{project-name}.1ab5.starter-us-east-1.openshiftapps.com/api/greeting
{"content":"Hello, World!"}
----

. Use `curl` to execute a `GET` request with the `name` URL parameter against the booster. You can also use a browser to do this.
+
[source,bash,options="nowrap",subs="attributes+"]
----
$ curl http://{app-name}-{project-name}.1ab5.starter-us-east-1.openshiftapps.com/api/greeting?name=Sarah
{"content":"Hello, Sarah!"}
----

- TODO -> add content of "include::rest-level-0-mission-form-note.adoc"

== Running Integration Tests

This booster contains a set of integration tests.
To run them, you must be connected to an OpenShift instance and select the project that will be used for testing.

To run the integration tests, execute the following command:

[source,bash,option="nowrap"]
--
$ mvn clean verify -Popenshift,openshift-it
--


[[about_rest]]
== REST Resources

More background and related information on REST can be found here:

* link:https://www.ics.uci.edu/~fielding/pubs/dissertation/rest_arch_style.htm[Architectural Styles and
the Design of Network-based Software Architectures - Representational State Transfer (REST)]
* link:https://martinfowler.com/articles/richardsonMaturityModel.html[Richardson Maturity Model]
* link:https://www.jcp.org/en/jsr/detail?id=311[JSR 311: JAX-RS: The JavaTM API for RESTful Web Services]

ifdef::http-api-spring-boot-tomcat[]
* link:https://spring.io/guides/gs/rest-service/[Building a RESTful Service with Spring]
endif::http-api-spring-boot-tomcat[]

ifdef::http-api-vertx[]
* link:http://vertx.io/blog/some-rest-with-vert-x/[Some Rest with {VertX}]
endif::http-api-vertx[]

ifdef::http-api-wf-swarm[]
* link:http://resteasy.jboss.org/docs.html[RESTEasy Documentation]
endif::http-api-wf-swarm[]

ifndef::http-api-spring-boot-tomcat[]
* link:{link-http-api-level-0-spring-boot-tomcat-booster}[{mission-http-api-spring-boot-tomcat-guide-name}]
endif::http-api-spring-boot-tomcat[]

ifndef::http-api-vertx[]
* link:{link-http-api-level-0-vertx-booster}[{mission-http-api-vertx-guide-name}]
endif::http-api-vertx[]

ifndef::http-api-wf-swarm[]
* link:{link-http-api-level-0-wf-swarm-booster}[{mission-http-api-wf-swarm-guide-name}]
endif::http-api-wf-swarm[]



